local M = {}

-- LSP kind -> highlight group, shared by the completion, breadcrumb and outline plugins below.
local kinds = {
	Array = "Type",
	Boolean = "Boolean",
	Class = "Type",
	Color = "Special",
	Constant = "Constant",
	Constructor = "@constructor",
	Copilot = "String",
	Enum = "Type",
	EnumMember = "Constant",
	Event = "Type",
	Field = "@variable.member",
	File = "Directory",
	Folder = "Directory",
	Function = "Function",
	Interface = "Type",
	Key = "Identifier",
	Keyword = "Keyword",
	Method = "@function.method",
	Module = "@module",
	Namespace = "@module",
	Null = "Type",
	Number = "Number",
	Object = "Type",
	Operator = "Operator",
	Package = "@module",
	Property = "@property",
	Reference = "Special",
	Snippet = "Special",
	String = "String",
	Struct = "Type",
	Text = "@variable",
	TypeParameter = "Type",
	Unit = "Number",
	Value = "String",
	Variable = "@variable",
}

---@param colors AzulejoColors
---@param config? AzulejoConfig
function M.setup(colors, config)
	config = config or require("azulejo-brutalism").config
	local theme = colors.theme
	local hl = {
		-- Gitsigns
		GitSignsAdd = { fg = theme.vcs.added, bg = theme.ui.bg_gutter },
		GitSignsChange = { fg = theme.vcs.changed, bg = theme.ui.bg_gutter },
		GitSignsDelete = { fg = theme.vcs.removed, bg = theme.ui.bg_gutter },
		-- Neogit
		NeogitDiffContextHighlight = { bg = theme.diff.change },
		NeogitHunkHeader = { fg = theme.ui.primary },
		NeogitHunkHeaderHighlight = { fg = theme.syn.constant, bg = theme.diff.change },
		NeogitDiffAddHighlight = { bg = theme.diff.add },
		NeogitDiffDeleteHighlight = { bg = theme.diff.delete },
		-- TreeSitter Extensions
		TreesitterContext = { link = "Folded" },
		TreesitterContextLineNumber = { fg = theme.ui.special, bg = theme.ui.bg_gutter },
		TreesitterContextBottom = { underline = true, sp = theme.ui.border },
		-- Telescope
		TelescopeBorder = { fg = theme.ui.border, bg = theme.ui.bg },
		TelescopeTitle = { fg = theme.ui.primary, bold = true },
		TelescopeSelection = { bg = theme.ui.bg_tile },
		TelescopeSelectionCaret = { fg = theme.ui.accent, bg = theme.ui.bg_tile, bold = true },
		TelescopeMatching = { fg = theme.ui.primary, bold = true },
		TelescopeResultsClass = { link = "Structure" },
		TelescopeResultsStruct = { link = "Structure" },
		TelescopeResultsField = { link = "@variable.member" },
		TelescopeResultsMethod = { link = "Function" },
		TelescopeResultsVariable = { link = "@variable" },
		-- NvimTree
		NvimTreeNormal = { fg = theme.ui.fg, bg = theme.ui.bg_m1 },
		NvimTreeNormalNC = { link = "NvimTreeNormal" },
		NvimTreeRootFolder = { fg = theme.ui.primary, bold = true },
		NvimTreeGitDirty = { fg = theme.vcs.changed },
		NvimTreeGitNew = { fg = theme.vcs.added },
		NvimTreeGitDeleted = { fg = theme.vcs.removed },
		NvimTreeGitStaged = { fg = theme.vcs.added },
		NvimTreeSpecialFile = { fg = theme.syn.special1 },
		NvimTreeImageFile = { fg = theme.syn.type },
		NvimTreeSymlink = { link = "Type" },
		NvimTreeFolderName = { link = "Directory" },
		NvimTreeExecFile = { fg = theme.syn.string, bold = true },
		NvimTreeOpenedFile = { fg = theme.syn.special1, italic = true },
		NvimTreeWinSeparator = { link = "WinSeparator" },
		NvimTreeWindowPicker = { fg = theme.ui.on_accent, bg = theme.ui.accent, bold = true },
		-- NeoTree
		NeoTreeNormal = { fg = theme.ui.fg, bg = theme.ui.bg_m1 },
		NeoTreeNormalNC = { link = "NeoTreeNormal" },
		NeoTreeTabInactive = { link = "TabLine" },
		NeoTreeTabActive = { link = "TabLineSel" },
		NeoTreeTabSeparatorInactive = { link = "NeoTreeTabInactive" },
		NeoTreeTabSeparatorActive = { link = "NeoTreeTabActive" },
		NeoTreeRootName = { fg = theme.ui.primary, bold = true },
		NeoTreeDirectoryName = { fg = theme.ui.fg },
		NeoTreeDirectoryIcon = { fg = theme.ui.primary },
		NeoTreeModified = { link = "String" },
		NeoTreeGitModified = { fg = theme.vcs.changed },
		NeoTreeGitAdded = { fg = theme.vcs.added },
		NeoTreeGitDeleted = { fg = theme.vcs.removed },
		NeoTreeGitStaged = { fg = theme.vcs.added },
		NeoTreeGitConflict = { fg = theme.diag.error },
		NeoTreeGitUntracked = { fg = theme.vcs.added },
		NeoTreeGitUnstaged = { link = "NeoTreeGitModified", default = true },
		NeoTreeIndentMarker = { link = "NonText" },
		-- Dashboard
		DashboardShortCut = { fg = theme.ui.accent },
		DashboardHeader = { fg = theme.ui.primary, bold = true },
		DashboardCenter = { fg = theme.ui.fg },
		DashboardFooter = { fg = theme.syn.comment },
		DashboardDesc = { fg = theme.ui.fg },
		DashboardKey = { fg = theme.ui.accent, bold = true },
		DashboardIcon = { fg = theme.ui.primary },
		-- Notify
		NotifyBackground = { bg = theme.ui.bg },
		NotifyERRORBorder = { link = "DiagnosticError" },
		NotifyWARNBorder = { link = "DiagnosticWarn" },
		NotifyINFOBorder = { link = "DiagnosticInfo" },
		NotifyHINTBorder = { link = "DiagnosticHint" },
		NotifyDEBUGBorder = { link = "Debug" },
		NotifyTRACEBorder = { link = "Comment" },
		NotifyERRORIcon = { link = "DiagnosticError" },
		NotifyWARNIcon = { link = "DiagnosticWarn" },
		NotifyINFOIcon = { link = "DiagnosticInfo" },
		NotifyHINTIcon = { link = "DiagnosticHint" },
		NotifyDEBUGIcon = { link = "Debug" },
		NotifyTRACEIcon = { link = "Comment" },
		NotifyERRORTitle = { link = "DiagnosticError" },
		NotifyWARNTitle = { link = "DiagnosticWarn" },
		NotifyINFOTitle = { link = "DiagnosticInfo" },
		NotifyHINTTitle = { link = "DiagnosticHint" },
		NotifyDEBUGTitle = { link = "Debug" },
		NotifyTRACETitle = { link = "Comment" },
		-- Dap-UI
		DapUIScope = { link = "Special" },
		DapUIType = { link = "Type" },
		DapUIModifiedValue = { fg = theme.syn.special1, bold = true },
		DapUIDecoration = { fg = theme.ui.float.fg_border },
		DapUIThread = { fg = theme.ui.primary },
		DapUIStoppedThread = { fg = theme.syn.special1 },
		DapUISource = { fg = theme.syn.special2 },
		DapUILineNumber = { fg = theme.syn.special1 },
		DapUIFloatBorder = { fg = theme.ui.float.fg_border },
		DapUIWatchesEmpty = { fg = theme.diag.error },
		DapUIWatchesValue = { fg = theme.syn.identifier },
		DapUIWatchesError = { fg = theme.diag.error },
		DapUIBreakpointsPath = { link = "Directory" },
		DapUIBreakpointsInfo = { fg = theme.diag.info },
		DapUIBreakpointsCurrentLine = { fg = theme.ui.accent, bold = true },
		DapUIBreakpointsDisabledLine = { link = "Comment" },
		DapUIStepOver = { fg = theme.syn.special1 },
		DapUIStepInto = { fg = theme.syn.special1 },
		DapUIStepBack = { fg = theme.syn.special1 },
		DapUIStepOut = { fg = theme.syn.special1 },
		DapUIStop = { fg = theme.diag.error },
		DapUIPlayPause = { fg = theme.syn.string },
		DapUIRestart = { fg = theme.syn.string },
		DapUIUnavailable = { fg = theme.syn.comment },
		-- Floaterm
		FloatermBorder = { fg = theme.ui.float.fg_border, bg = theme.ui.bg },
		-- NeoVim
		healthError = { fg = theme.diag.error },
		healthSuccess = { fg = theme.diag.ok },
		healthWarning = { fg = theme.diag.warning },
		-- Cmp
		CmpDocumentation = { link = "NormalFloat" },
		CmpDocumentationBorder = { link = "FloatBorder" },
		CmpCompletion = { link = "Pmenu" },
		CmpCompletionSel = { link = "PmenuSel" },
		CmpCompletionBorder = { fg = theme.ui.border, bg = theme.ui.pmenu.bg },
		CmpCompletionThumb = { link = "PmenuThumb" },
		CmpCompletionSbar = { link = "PmenuSbar" },
		CmpItemAbbr = { fg = theme.ui.pmenu.fg },
		CmpItemAbbrDeprecated = { fg = theme.syn.comment, strikethrough = true },
		CmpItemAbbrMatch = { fg = theme.ui.primary, bold = true },
		CmpItemAbbrMatchFuzzy = { link = "CmpItemAbbrMatch" },
		CmpItemKind = { fg = theme.syn.type },
		CmpItemKindDefault = { fg = theme.syn.type },
		CmpItemMenu = { fg = theme.ui.fg_dim },
		CmpGhostText = { fg = theme.syn.comment },
		-- blink.cmp
		BlinkCmpMenu = { link = "Pmenu" },
		BlinkCmpMenuSelection = { link = "PmenuSel" },
		BlinkCmpMenuBorder = { fg = theme.ui.border, bg = theme.ui.pmenu.bg },
		BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
		BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
		BlinkCmpLabel = { fg = theme.ui.pmenu.fg },
		BlinkCmpLabelMatch = { fg = theme.ui.primary, bold = true },
		BlinkCmpLabelDetails = { fg = theme.syn.comment },
		BlinkCmpLabelDeprecated = { fg = theme.syn.comment, strikethrough = true },
		BlinkCmpGhostText = { fg = theme.syn.comment },
		BlinkCmpDoc = { link = "NormalFloat" },
		BlinkCmpDocBorder = { link = "FloatBorder" },
		BlinkCmpDocCursorLine = { link = "Visual" },
		BlinkCmpSignatureHelp = { link = "NormalFloat" },
		BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
		BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },
		BlinkCmpKind = { fg = theme.syn.type },
		-- IndentBlankline
		IndentBlanklineChar = { fg = theme.ui.whitespace },
		IndentBlanklineSpaceChar = { fg = theme.ui.whitespace },
		IndentBlanklineSpaceCharBlankline = { fg = theme.ui.whitespace },
		IndentBlanklineContextChar = { fg = theme.ui.special },
		IndentBlanklineContextStart = { sp = theme.ui.special, underline = true },
		IblIndent = { fg = theme.ui.whitespace },
		IblWhitespace = { fg = theme.ui.whitespace },
		IblScope = { fg = theme.ui.special },
		-- Lazy
		LazyProgressTodo = { fg = theme.ui.nontext },
		-- Trouble
		TroubleIndent = { fg = theme.ui.whitespace },
		TroublePos = { fg = theme.ui.special },
		-- Nvim-Navic
		NavicText = { fg = theme.ui.fg },
		NavicSeparator = { fg = theme.ui.fg },
		-- Snacks
		SnacksPickerMatch = { fg = theme.ui.primary, bold = true },
		SnacksPickerDir = { fg = theme.ui.special },
		SnacksPickerListCursorLine = { bg = theme.ui.bg_tile },
		SnacksIndent = { fg = theme.ui.whitespace },
		SnacksIndentScope = { fg = theme.ui.special },
		SnacksDashboardHeader = { fg = theme.ui.primary, bold = true },
		SnacksDashboardKey = { fg = theme.ui.accent, bold = true },
		SnacksDashboardDesc = { fg = theme.ui.fg },
		SnacksDashboardIcon = { fg = theme.ui.primary },
		SnacksDashboardFooter = { fg = theme.ui.special },
		-- which-key
		WhichKey = { fg = theme.ui.accent, bold = true },
		WhichKeyGroup = { fg = theme.ui.primary },
		WhichKeyDesc = { fg = theme.ui.fg },
		WhichKeySeparator = { fg = theme.ui.special },
		-- flash
		FlashLabel = { fg = theme.ui.on_accent, bg = theme.ui.accent, bold = true },
		FlashMatch = { fg = theme.ui.primary, bg = theme.ui.bg_tile },
		FlashCurrent = { link = "IncSearch" },
		-- noice
		NoiceCmdlineIcon = { fg = theme.ui.primary },
		NoiceCmdlinePopupBorder = { link = "FloatBorder" },
		-- bufferline
		BufferLineFill = { bg = theme.ui.bg_m3 },
		BufferLineBufferSelected = { fg = theme.ui.fg, bold = true },
		BufferLineIndicatorSelected = { fg = theme.ui.accent },

		-- Mini
		MiniAnimateCursor = { reverse = true, nocombine = true },
		MiniAnimateNormalFloat = { link = "NormalFloat" },

		MiniClueBorder = { link = "FloatBorder" },
		MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
		MiniClueDescSingle = { link = "NormalFloat" },
		MiniClueNextKey = { link = "DiagnosticFloatingHint" },
		MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
		MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
		MiniClueTitle = { link = "FloatTitle" },

		MiniCompletionActiveParameter = { underline = true },

		MiniCursorword = { underline = true },
		MiniCursorwordCurrent = { underline = true },

		MiniDepsChangeAdded = { link = "diffAdded" },
		MiniDepsChangeRemoved = { link = "diffRemoved" },
		MiniDepsHint = { fg = theme.diag.hint },
		MiniDepsInfo = { fg = theme.diag.info },
		MiniDepsMsgBreaking = { fg = theme.diag.warning },
		MiniDepsPlaceholder = { link = "Comment" },
		MiniDepsTitle = { link = "Title" },
		MiniDepsTitleError = { link = "DiffDelete" },
		MiniDepsTitleSame = { link = "DiffText" },
		MiniDepsTitleUpdate = { link = "DiffAdd" },

		MiniDiffSignAdd = { fg = theme.vcs.added, bg = theme.ui.bg_gutter },
		MiniDiffSignChange = { fg = theme.vcs.changed, bg = theme.ui.bg_gutter },
		MiniDiffSignDelete = { fg = theme.vcs.removed, bg = theme.ui.bg_gutter },
		MiniDiffOverAdd = { link = "DiffAdd" },
		MiniDiffOverChange = { link = "DiffText" },
		MiniDiffOverContext = { link = "DiffChange" },
		MiniDiffOverDelete = { link = "DiffDelete" },

		MiniFilesBorder = { link = "FloatBorder" },
		MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
		MiniFilesCursorLine = { bg = theme.ui.bg_tile },
		MiniFilesDirectory = { link = "Directory" },
		MiniFilesFile = { fg = theme.ui.fg },
		MiniFilesNormal = { link = "NormalFloat" },
		MiniFilesTitle = { fg = theme.ui.special, bg = theme.ui.float.bg_border, bold = true },
		MiniFilesTitleFocused = { fg = theme.ui.primary, bg = theme.ui.float.bg_border, bold = true },

		MiniHipatternsFixme = { fg = theme.ui.fg_reverse, bg = theme.diag.error, bold = true },
		MiniHipatternsHack = { fg = theme.ui.on_accent, bg = theme.ui.accent, bold = true },
		MiniHipatternsNote = { fg = theme.ui.fg_reverse, bg = theme.ui.primary, bold = true },
		MiniHipatternsTodo = { link = "Todo" },

		MiniIconsAzure = { fg = theme.ui.primary },
		MiniIconsBlue = { fg = theme.ui.primary },
		MiniIconsCyan = { fg = theme.syn.special1 },
		MiniIconsGreen = { fg = theme.syn.string },
		MiniIconsGrey = { fg = theme.ui.special },
		MiniIconsOrange = { fg = theme.syn.constant },
		MiniIconsPurple = { fg = theme.syn.type },
		MiniIconsRed = { fg = theme.diag.error },
		MiniIconsYellow = { fg = theme.syn.constant },

		MiniIndentscopeSymbol = { fg = theme.ui.special },
		MiniIndentscopePrefix = { nocombine = true }, -- Make it invisible

		MiniJump = { link = "SpellRare" },

		MiniJump2dDim = { link = "Comment" },
		MiniJump2dSpot = { fg = theme.ui.accent, bold = true, nocombine = true },
		MiniJump2dSpotAhead = { fg = theme.diag.hint, bg = theme.ui.bg_dim, nocombine = true },
		MiniJump2dSpotUnique = { fg = theme.ui.primary, bold = true, nocombine = true },

		MiniMapNormal = { link = "NormalFloat" },
		MiniMapSymbolCount = { link = "Special" },
		MiniMapSymbolLine = { link = "Title" },
		MiniMapSymbolView = { link = "Delimiter" },

		MiniNotifyBorder = { link = "FloatBorder" },
		MiniNotifyNormal = { link = "NormalFloat" },
		MiniNotifyTitle = { link = "FloatTitle" },

		MiniOperatorsExchangeFrom = { link = "IncSearch" },

		MiniPickBorder = { link = "FloatBorder" },
		MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
		MiniPickBorderText = { link = "FloatTitle" },
		MiniPickIconDirectory = { link = "Directory" },
		MiniPickIconFile = { link = "MiniPickNormal" },
		MiniPickHeader = { link = "DiagnosticFloatingHint" },
		MiniPickMatchCurrent = { bg = theme.ui.bg_tile },
		MiniPickMatchMarked = { link = "Visual" },
		MiniPickMatchRanges = { fg = theme.ui.primary, bold = true },
		MiniPickNormal = { link = "NormalFloat" },
		MiniPickPreviewLine = { link = "CursorLine" },
		MiniPickPreviewRegion = { link = "IncSearch" },
		MiniPickPrompt = { fg = theme.ui.primary, bg = theme.ui.float.bg_border },

		MiniStarterCurrent = { nocombine = true },
		MiniStarterFooter = { fg = theme.syn.deprecated },
		MiniStarterHeader = { link = "Title" },
		MiniStarterInactive = { link = "Comment" },
		MiniStarterItem = { link = "Normal" },
		MiniStarterItemBullet = { link = "Delimiter" },
		MiniStarterItemPrefix = { fg = theme.ui.accent },
		MiniStarterSection = { fg = theme.diag.ok },
		MiniStarterQuery = { fg = theme.diag.info },

		MiniStatuslineDevinfo = { fg = theme.ui.fg_dim, bg = theme.ui.bg_p1 },
		MiniStatuslineFileinfo = { fg = theme.ui.fg_dim, bg = theme.ui.bg_p1 },
		MiniStatuslineFilename = { fg = theme.ui.fg_dim, bg = theme.ui.bg_dim },
		MiniStatuslineInactive = { link = "StatusLineNC" },
		MiniStatuslineModeCommand = { fg = theme.ui.on_accent, bg = theme.ui.accent, bold = true },
		MiniStatuslineModeInsert = { fg = theme.ui.fg_reverse, bg = theme.diag.ok, bold = true },
		MiniStatuslineModeNormal = { fg = theme.ui.fg_reverse, bg = theme.ui.primary, bold = true },
		MiniStatuslineModeOther = { fg = theme.ui.fg_reverse, bg = theme.syn.special1, bold = true },
		MiniStatuslineModeReplace = { fg = theme.ui.fg_reverse, bg = theme.diag.error, bold = true },
		MiniStatuslineModeVisual = { fg = theme.ui.fg_reverse, bg = theme.syn.type, bold = true },

		MiniSurround = { link = "IncSearch" },

		MiniTablineCurrent = { fg = theme.ui.fg_reverse, bg = theme.ui.primary, bold = true },
		MiniTablineFill = { link = "TabLineFill" },
		MiniTablineHidden = { fg = theme.ui.special, bg = theme.ui.bg_m3 },
		MiniTablineModifiedCurrent = { fg = theme.ui.on_accent, bg = theme.ui.accent, bold = true },
		MiniTablineModifiedHidden = { fg = theme.ui.bg_m3, bg = theme.ui.special },
		MiniTablineModifiedVisible = { fg = theme.ui.bg_m3, bg = theme.ui.special, bold = true },
		MiniTablineTabpagesection = { fg = theme.ui.fg_reverse, bg = theme.ui.primary, bold = true },
		MiniTablineVisible = { fg = theme.ui.fg, bg = theme.ui.bg_m3, bold = true },

		MiniTestEmphasis = { bold = true },
		MiniTestFail = { fg = theme.diag.error, bold = true },
		MiniTestPass = { fg = theme.diag.ok, bold = true },

		MiniTrailspace = { bg = theme.vcs.removed },

		-- Neotest
		NeotestAdapterName = { fg = theme.syn.special3 },
		NeotestDir = { fg = theme.ui.primary },
		NeotestExpandMarker = { fg = theme.syn.punct, bold = true },
		NeotestFailed = { fg = theme.diag.error },
		NeotestFile = { fg = theme.ui.primary },
		NeotestFocused = { bold = true, underline = true },
		NeotestIndent = { fg = theme.ui.special, bold = true },
		NeotestMarked = { fg = theme.ui.accent, italic = true },
		NeotestNamespace = { fg = theme.ui.primary },
		NeotestPassed = { fg = theme.diag.ok },
		NeotestRunning = { fg = theme.vcs.changed },
		NeotestWinSelect = { fg = theme.diag.hint },
		NeotestSkipped = { fg = theme.syn.special1 },
		NeotestTarget = { fg = theme.syn.special3 },
		NeotestTest = { fg = theme.ui.float.fg },
		NeotestUnknown = { fg = theme.syn.deprecated },
		NeotestWatching = { fg = theme.vcs.changed },
	}

	for kind, link in pairs(kinds) do
		hl["CmpItemKind" .. kind] = { link = link }
		hl["BlinkCmpKind" .. kind] = { link = link }
		hl["NavicIcons" .. kind] = { link = link }
		hl["Aerial" .. kind .. "Icon"] = { link = link }
	end

	return hl
end

return M
